#!/bin/bash

# Function to add, commit, and push changes
add_commit_push() {
    git add "$1"
    git commit -m "$2"
    git push 
}

# Add and commit each file with a description
add_commit_push "0-preprocessor" "Add 0-preprocessor file"
add_commit_push "1-compiler" "Add 1-compiler file"
add_commit_push "2-assembler" "Add 2-assembler file"
add_commit_push "3-name" "Add 3-name file"
add_commit_push "4-puts.c" "Add 4-puts.c file"
add_commit_push "5-printf.c" "Add 5-printf.c file"
add_commit_push "6-size.c" "Add 6-size.c file"
add_commit_push "100-intel" "Add 100-intel file"
add_commit_push "101-quote.c" "Add 101-quote.c file"

echo "Files added, committed, and pushed successfully!"

